## Score : 0.008810	

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
cdtx_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/cdtx_train.csv')
dp_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/dp_train.csv')
remit_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/remit_train.csv')

In [8]:
cdtx_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/cdtx_test.csv')
dp_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/dp_test.csv')
remit_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/remit_test.csv')

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [10]:
cdtx_X = cdtx_train.iloc[:,1:-1].values
cdtx_y = cdtx_train.iloc[:,-1].values

In [11]:
dp_X = dp_train.iloc[:,1:-1].values
dp_y = dp_train.iloc[:,-1].values

In [12]:
remit_X = remit_train.iloc[:,1:-1].values
remit_y = remit_train.iloc[:,-1].values

In [13]:
cdtx_test_new = cdtx_test.iloc[:,1:].values

In [14]:
dp_test_new = dp_test.iloc[:,1:].values

In [15]:
remit_test_new = remit_test.iloc[:,1:].values

In [16]:
cdtx_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,5,8]),('standardscaler',StandardScaler(),[2,6,7])], remainder='passthrough')
cdtx_X = cdtx_ct.fit_transform(cdtx_X)
cdtx_X

<48107x366 sparse matrix of type '<class 'numpy.float64'>'
	with 432963 stored elements in Compressed Sparse Row format>

In [17]:
dp_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,5,6,8,9,10,11,12,13,15]),('standardscaler',StandardScaler(),[2,7,14])], remainder='passthrough')
dp_X = dp_ct.fit_transform(dp_X)
dp_X

<164030x1874 sparse matrix of type '<class 'numpy.float64'>'
	with 2624480 stored elements in Compressed Sparse Row format>

In [18]:
remit_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,7]),('standardscaler',StandardScaler(),[2,5,6])], remainder='passthrough')
remit_X = remit_ct.fit_transform(remit_X)
remit_X

<5438x280 sparse matrix of type '<class 'numpy.float64'>'
	with 43504 stored elements in Compressed Sparse Row format>

In [19]:
cdtx_test_X = cdtx_ct.transform(cdtx_test_new)

In [20]:
dp_test_X = dp_ct.transform(dp_test_new)

In [21]:
remit_test_X = remit_ct.transform(remit_test_new)

In [24]:
regressor_cdtx = KNeighborsClassifier(n_neighbors=20, metric='minkowski',p=2)
regressor_cdtx.fit(cdtx_X, cdtx_y)

KNeighborsClassifier(n_neighbors=20)

In [25]:
regressor_dp = KNeighborsClassifier(n_neighbors=20, metric='minkowski',p=2)
regressor_dp.fit(dp_X, dp_y)

KNeighborsClassifier(n_neighbors=20)

In [26]:
regressor_remit = KNeighborsClassifier(n_neighbors=20, metric='minkowski',p=2)
regressor_remit.fit(remit_X, remit_y)

KNeighborsClassifier(n_neighbors=20)

In [29]:
cdtx_y_pred = regressor_cdtx.predict_proba(cdtx_test_X)
cdtx_y_pred

array([[1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       ...,
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.95, 0.05]])

In [30]:
cdtx_y_ans = pd.DataFrame(cdtx_y_pred)

In [31]:
cdtx_y_ans

0     1
0     1.00  0.00
1     1.00  0.00
2     1.00  0.00
3     1.00  0.00
4     1.00  0.00
...    ...   ...
2123  1.00  0.00
2124  1.00  0.00
2125  1.00  0.00
2126  1.00  0.00
2127  0.95  0.05

[2128 rows x 2 columns]

In [32]:
cdtx_y_ans[cdtx_y_ans[1]!=0]

0     1
409   0.95  0.05
411   0.85  0.15
412   0.85  0.15
413   0.85  0.15
414   0.85  0.15
...    ...   ...
2104  0.85  0.15
2105  0.85  0.15
2106  0.85  0.15
2111  0.90  0.10
2127  0.95  0.05

[365 rows x 2 columns]

In [33]:
dp_y_pred = regressor_dp.predict_proba(dp_test_X)
dp_y_pred

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [34]:
dp_y_ans = pd.DataFrame(dp_y_pred)
dp_y_ans

0    1
0      1.0  0.0
1      1.0  0.0
2      1.0  0.0
3      1.0  0.0
4      1.0  0.0
...    ...  ...
13546  1.0  0.0
13547  1.0  0.0
13548  1.0  0.0
13549  1.0  0.0
13550  1.0  0.0

[13551 rows x 2 columns]

In [35]:
dp_y_ans[dp_y_ans[1]!=0]

0     1
63     0.95  0.05
105    0.95  0.05
108    0.85  0.15
193    0.95  0.05
199    0.95  0.05
...     ...   ...
13512  0.95  0.05
13529  0.70  0.30
13530  0.70  0.30
13531  0.70  0.30
13542  0.95  0.05

[1941 rows x 2 columns]

In [36]:
remit_y_pred = regressor_remit.predict_proba(remit_test_X)
remit_y_pred

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [37]:
remit_y_ans = pd.DataFrame(remit_y_pred)
remit_y_ans

0     1
0    1.00  0.00
1    1.00  0.00
2    1.00  0.00
3    1.00  0.00
4    1.00  0.00
..    ...   ...
532  0.85  0.15
533  1.00  0.00
534  1.00  0.00
535  1.00  0.00
536  1.00  0.00

[537 rows x 2 columns]

In [38]:
cdtx_ans = pd.DataFrame(cdtx_test['alert_key'])
cdtx_ans['probability'] = cdtx_y_ans[1]
cdtx_ans

alert_key  probability
0        352291         0.00
1        352291         0.00
2        352298         0.00
3        352298         0.00
4        353041         0.00
...         ...          ...
2123     364964         0.00
2124     364977         0.00
2125     364977         0.00
2126     364983         0.00
2127     364983         0.05

[2128 rows x 2 columns]

In [39]:
dp_ans = pd.DataFrame(dp_test['alert_key'])
dp_ans['probability'] = dp_y_ans[1]
dp_ans

alert_key  probability
0         352249          0.0
1         352249          0.0
2         352249          0.0
3         352249          0.0
4         352249          0.0
...          ...          ...
13546     364993          0.0
13547     364993          0.0
13548     364993          0.0
13549     364993          0.0
13550     364993          0.0

[13551 rows x 2 columns]

In [40]:
remit_ans = pd.DataFrame(remit_test['alert_key'])
remit_ans['probability'] = remit_y_ans[1]
remit_ans

alert_key  probability
0       352253         0.00
1       354177         0.00
2       354569         0.00
3       355347         0.00
4       356569         0.00
..         ...          ...
532     364673         0.15
533     364753         0.00
534     364775         0.00
535     364788         0.00
536     364993         0.00

[537 rows x 2 columns]

In [41]:
ans = pd.concat([cdtx_ans,dp_ans,remit_ans])

In [42]:
ans

alert_key  probability
0       352291         0.00
1       352291         0.00
2       352298         0.00
3       352298         0.00
4       353041         0.00
..         ...          ...
532     364673         0.15
533     364753         0.00
534     364775         0.00
535     364788         0.00
536     364993         0.00

[16216 rows x 2 columns]

In [43]:
ans['probability'] = ans['probability'].abs()

In [44]:
ans_mean = ans.groupby(['alert_key']).mean()

In [45]:
ans_mean

probability
alert_key             
352249        0.000000
352253        0.000000
352254        0.007692
352280        0.000000
352282        0.000000
...                ...
365001        0.035714
365004        0.000000
365008        0.001064
365009        0.100000
365073        0.007018

[1528 rows x 1 columns]

In [46]:
submit = pd.read_csv('/home/bill/moneylaundring/dataset/submit.csv')

In [47]:
submit['probability']=0

In [48]:
submit

alert_key  probability
0        357307            0
1        376329            0
2        373644            0
3        357668            0
4        354443            0
...         ...          ...
3845     364485            0
3846     363155            0
3847     368710            0
3848     358067            0
3849     372119            0

[3850 rows x 2 columns]

In [49]:
submit_new = pd.merge(submit, ans_mean, on=['alert_key'],how='left')

In [50]:
submit_new['probability_y'].fillna(0,inplace=True)

In [51]:
submit_final = submit_new.rename(columns={'probability_y':'probability'})

In [52]:
submit_final = submit_final[['alert_key','probability']]

In [53]:
submit_final = submit_final.sort_values(by ='probability', ascending=False)

In [54]:
submit_final

alert_key  probability
2554     362151        0.445
1327     354432        0.400
2108     361698        0.400
3432     357883        0.350
767      360292        0.350
...         ...          ...
1417     377353        0.000
1418     376495        0.000
1419     371930        0.000
1420     367929        0.000
3849     372119        0.000

[3850 rows x 2 columns]

In [55]:
submit_final.to_csv('/home/bill/moneylaundring/contest/submissions/knn.csv')