In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cdtx_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/cdtx_train.csv')
dp_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/dp_train.csv')
remit_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/remit_train.csv')
cdtx_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/cdtx_test.csv')
dp_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/dp_test.csv')
remit_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/remit_test.csv')

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [4]:
cdtx_X = cdtx_train.iloc[:,1:-1].values
cdtx_y = cdtx_train.iloc[:,-1].values

In [5]:
dp_X = dp_train.iloc[:,1:-1].values
dp_y = dp_train.iloc[:,-1].values

In [6]:
remit_X = remit_train.iloc[:,1:-1].values
remit_y = remit_train.iloc[:,-1].values

In [7]:
cdtx_test_new = cdtx_test.iloc[:,1:].values

In [8]:
dp_test_new = dp_test.iloc[:,1:].values

In [9]:
remit_test_new = remit_test.iloc[:,1:].values

In [10]:
cdtx_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,5,8]),('standardscaler',StandardScaler(),[2,6,7])], remainder='passthrough')
cdtx_X = cdtx_ct.fit_transform(cdtx_X)
cdtx_X

<48107x366 sparse matrix of type '<class 'numpy.float64'>'
	with 432963 stored elements in Compressed Sparse Row format>

In [11]:
dp_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,5,6,8,9,10,11,12,13,15]),('standardscaler',StandardScaler(),[2,7,14])], remainder='passthrough')
dp_X = dp_ct.fit_transform(dp_X)
dp_X

<164030x1874 sparse matrix of type '<class 'numpy.float64'>'
	with 2624480 stored elements in Compressed Sparse Row format>

In [12]:
remit_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,7]),('standardscaler',StandardScaler(),[2,5,6])], remainder='passthrough')
remit_X = remit_ct.fit_transform(remit_X)
remit_X

<5438x280 sparse matrix of type '<class 'numpy.float64'>'
	with 43504 stored elements in Compressed Sparse Row format>

In [13]:
cdtx_test_X = cdtx_ct.transform(cdtx_test_new)

In [14]:
dp_test_X = dp_ct.transform(dp_test_new)

In [15]:
remit_test_X = remit_ct.transform(remit_test_new)

In [16]:
regressor_cdtx = LogisticRegression(solver='sag',max_iter=10000)
regressor_cdtx.fit(cdtx_X, cdtx_y)

LogisticRegression(max_iter=10000, solver='sag')

In [17]:
regressor_dp = LogisticRegression(solver='sag',max_iter=10000)
regressor_dp.fit(dp_X, dp_y)

LogisticRegression(max_iter=10000, solver='sag')

In [18]:
regressor_remit= LogisticRegression(solver='sag',max_iter=1000)
regressor_remit.fit(remit_X, remit_y)

LogisticRegression(max_iter=1000, solver='sag')

In [24]:
cdtx_y_pred = regressor_cdtx.predict_proba(cdtx_test_X)
cdtx_y_pred

array([[9.99252657e-01, 7.47342967e-04],
       [9.99254453e-01, 7.45546927e-04],
       [9.99265563e-01, 7.34436833e-04],
       ...,
       [9.99008843e-01, 9.91156800e-04],
       [7.01864712e-01, 2.98135288e-01],
       [9.15286069e-01, 8.47139313e-02]])

In [25]:
cdtx_y_ans = pd.DataFrame(cdtx_y_pred)

In [26]:
cdtx_y_ans

0         1
0     0.999253  0.000747
1     0.999254  0.000746
2     0.999266  0.000734
3     0.999266  0.000734
4     0.999266  0.000734
...        ...       ...
2123  0.999298  0.000702
2124  0.999009  0.000991
2125  0.999009  0.000991
2126  0.701865  0.298135
2127  0.915286  0.084714

[2128 rows x 2 columns]

In [27]:
dp_y_pred = regressor_dp.predict_proba(dp_test_X)
dp_y_pred

array([[0.99536291, 0.00463709],
       [0.99521219, 0.00478781],
       [0.99536214, 0.00463786],
       ...,
       [0.97636627, 0.02363373],
       [0.99530182, 0.00469818],
       [0.99530817, 0.00469183]])

In [28]:
dp_y_ans = pd.DataFrame(dp_y_pred)
dp_y_ans

0         1
0      0.995363  0.004637
1      0.995212  0.004788
2      0.995362  0.004638
3      0.996208  0.003792
4      0.994917  0.005083
...         ...       ...
13546  0.995346  0.004654
13547  0.995309  0.004691
13548  0.976366  0.023634
13549  0.995302  0.004698
13550  0.995308  0.004692

[13551 rows x 2 columns]

In [31]:
remit_y_pred = regressor_remit.predict_proba(remit_test_X)
remit_y_pred

array([[0.96769181, 0.03230819],
       [0.96769614, 0.03230386],
       [0.96769608, 0.03230392],
       ...,
       [0.99785028, 0.00214972],
       [0.96468462, 0.03531538],
       [0.96127547, 0.03872453]])

In [32]:
remit_y_ans = pd.DataFrame(remit_y_pred)
remit_y_ans

0         1
0    0.967692  0.032308
1    0.967696  0.032304
2    0.967696  0.032304
3    0.967692  0.032308
4    0.967661  0.032339
..        ...       ...
532  0.945518  0.054482
533  0.997821  0.002179
534  0.997850  0.002150
535  0.964685  0.035315
536  0.961275  0.038725

[537 rows x 2 columns]

In [33]:
cdtx_ans = pd.DataFrame(cdtx_test['alert_key'])
cdtx_ans['probability'] = cdtx_y_ans[1]
cdtx_ans

alert_key  probability
0        352291     0.000747
1        352291     0.000746
2        352298     0.000734
3        352298     0.000734
4        353041     0.000734
...         ...          ...
2123     364964     0.000702
2124     364977     0.000991
2125     364977     0.000991
2126     364983     0.298135
2127     364983     0.084714

[2128 rows x 2 columns]

In [34]:
dp_ans = pd.DataFrame(dp_test['alert_key'])
dp_ans['probability'] = dp_y_ans[1]
dp_ans

alert_key  probability
0         352249     0.004637
1         352249     0.004788
2         352249     0.004638
3         352249     0.003792
4         352249     0.005083
...          ...          ...
13546     364993     0.004654
13547     364993     0.004691
13548     364993     0.023634
13549     364993     0.004698
13550     364993     0.004692

[13551 rows x 2 columns]

In [35]:
remit_ans = pd.DataFrame(remit_test['alert_key'])
remit_ans['probability'] = remit_y_ans[1]
remit_ans

alert_key  probability
0       352253     0.032308
1       354177     0.032304
2       354569     0.032304
3       355347     0.032308
4       356569     0.032339
..         ...          ...
532     364673     0.054482
533     364753     0.002179
534     364775     0.002150
535     364788     0.035315
536     364993     0.038725

[537 rows x 2 columns]

In [36]:
ans = pd.concat([cdtx_ans,dp_ans,remit_ans])

In [37]:
ans

alert_key  probability
0       352291     0.000747
1       352291     0.000746
2       352298     0.000734
3       352298     0.000734
4       353041     0.000734
..         ...          ...
532     364673     0.054482
533     364753     0.002179
534     364775     0.002150
535     364788     0.035315
536     364993     0.038725

[16216 rows x 2 columns]

In [38]:
ans['probability'] = ans['probability'].abs()

In [39]:
ans_mean = ans.groupby(['alert_key']).mean()

In [40]:
ans_mean

probability
alert_key             
352249        0.004147
352253        0.023464
352254        0.002796
352280        0.000617
352282        0.001222
...                ...
365001        0.020371
365004        0.000525
365008        0.000917
365009        0.007771
365073        0.001596

[1528 rows x 1 columns]

In [41]:
submit = pd.read_csv('/home/bill/moneylaundring/dataset/submit.csv')

In [43]:
submit['probability']=0

In [44]:
submit

alert_key  probability
0        357307            0
1        376329            0
2        373644            0
3        357668            0
4        354443            0
...         ...          ...
3845     364485            0
3846     363155            0
3847     368710            0
3848     358067            0
3849     372119            0

[3850 rows x 2 columns]

In [45]:
submit_new = pd.merge(submit, ans_mean, on=['alert_key'],how='left')

In [46]:
submit_new['probability_y'].fillna(0,inplace=True)

In [47]:
submit_final = submit_new.rename(columns={'probability_y':'probability'})

In [48]:
submit_final = submit_final[['alert_key','probability']]

In [49]:
submit_final = submit_final.sort_values(by ='probability', ascending=False)

In [50]:
submit_final

alert_key  probability
2738     360601     0.396486
633      359499     0.361923
979      361303     0.351404
2642     362488     0.339640
1157     364705     0.335835
...         ...          ...
1595     377601     0.000000
1596     369441     0.000000
1599     374756     0.000000
1600     367411     0.000000
3849     372119     0.000000

[3850 rows x 2 columns]

In [51]:
submit_final.to_csv('/home/bill/moneylaundring/contest/submissions/logistic_regression_submit.csv')