In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
cdtx_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/cdtx_train.csv')
dp_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/dp_train.csv')
remit_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/remit_train.csv')
cdtx_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/cdtx_test.csv')
dp_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/dp_test.csv')
remit_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/remit_test.csv')

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor

In [9]:
cdtx_X = cdtx_train.iloc[:,1:-1].values
cdtx_y = cdtx_train.iloc[:,-1].values

In [10]:
dp_X = dp_train.iloc[:,1:-1].values
dp_y = dp_train.iloc[:,-1].values

In [11]:
remit_X = remit_train.iloc[:,1:-1].values
remit_y = remit_train.iloc[:,-1].values

In [12]:
cdtx_test_new = cdtx_test.iloc[:,1:].values

In [13]:
dp_test_new = dp_test.iloc[:,1:].values

In [14]:
remit_test_new = remit_test.iloc[:,1:].values

In [15]:
cdtx_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,5,8]),('standardscaler',StandardScaler(),[2,6,7])], remainder='passthrough')
cdtx_X = cdtx_ct.fit_transform(cdtx_X)
cdtx_X

<48107x366 sparse matrix of type '<class 'numpy.float64'>'
	with 432963 stored elements in Compressed Sparse Row format>

In [16]:
dp_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,5,6,8,9,10,11,12,13,15]),('standardscaler',StandardScaler(),[2,7,14])], remainder='passthrough')
dp_X = dp_ct.fit_transform(dp_X)
dp_X

<164030x1874 sparse matrix of type '<class 'numpy.float64'>'
	with 2624480 stored elements in Compressed Sparse Row format>

In [17]:
remit_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,7]),('standardscaler',StandardScaler(),[2,5,6])], remainder='passthrough')
remit_X = remit_ct.fit_transform(remit_X)
remit_X

<5438x280 sparse matrix of type '<class 'numpy.float64'>'
	with 43504 stored elements in Compressed Sparse Row format>

In [18]:
cdtx_test_X = cdtx_ct.transform(cdtx_test_new)

In [19]:
dp_test_X = dp_ct.transform(dp_test_new)

In [20]:
remit_test_X = remit_ct.transform(remit_test_new)

In [23]:
regressor_cdtx = RandomForestRegressor(n_estimators=300, criterion='mse', random_state= 42)
regressor_cdtx.fit(cdtx_X, cdtx_y)

/home/bill/anaconda3/envs/moneylaundring/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


RandomForestRegressor(criterion='mse', n_estimators=300, random_state=42)

In [24]:
regressor_dp = RandomForestRegressor(n_estimators=300, criterion='mse', random_state= 42)
regressor_dp.fit(dp_X, dp_y)

/home/bill/anaconda3/envs/moneylaundring/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


RandomForestRegressor(criterion='mse', n_estimators=300, random_state=42)

In [25]:
regressor_remit = RandomForestRegressor(n_estimators=300, criterion='mse', random_state= 42)
regressor_remit.fit(remit_X, remit_y)

/home/bill/anaconda3/envs/moneylaundring/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


RandomForestRegressor(criterion='mse', n_estimators=300, random_state=42)

In [27]:
cdtx_y_pred = regressor_cdtx.predict(cdtx_test_X)
cdtx_y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [28]:
cdtx_y_ans = pd.DataFrame(cdtx_y_pred)

In [30]:
cdtx_y_ans[cdtx_y_ans[0]!=0]

0
411   0.006667
412   0.006667
413   0.006667
414   0.006667
415   0.006667
416   0.006667
417   0.006667
418   0.006667
419   0.006667
420   0.006667
421   0.006667
422   0.006667
423   0.006667
424   0.006667
425   0.006667
426   0.006667
1407  0.006667
1440  0.020000
1441  0.020000
1442  0.020000
1875  0.073333
1876  0.073333
1877  0.073333
1942  0.003333
1956  0.003333
2060  0.003333

In [32]:
dp_y_pred = regressor_dp.predict(dp_test_X)
dp_y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [33]:
dp_y_ans = pd.DataFrame(dp_y_pred)
dp_y_ans

0
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
...    ...
13546  0.0
13547  0.0
13548  0.0
13549  0.0
13550  0.0

[13551 rows x 1 columns]

In [35]:
remit_y_pred = regressor_remit.predict(remit_test_X)
remit_y_pred

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00666667, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [36]:
remit_y_ans = pd.DataFrame(remit_y_pred)
remit_y_ans

0
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
..   ...
532  0.0
533  0.0
534  0.0
535  0.0
536  0.0

[537 rows x 1 columns]

In [37]:
cdtx_ans = pd.DataFrame(cdtx_test['alert_key'])
cdtx_ans['probability'] = cdtx_y_ans[0]
cdtx_ans

alert_key  probability
0        352291          0.0
1        352291          0.0
2        352298          0.0
3        352298          0.0
4        353041          0.0
...         ...          ...
2123     364964          0.0
2124     364977          0.0
2125     364977          0.0
2126     364983          0.0
2127     364983          0.0

[2128 rows x 2 columns]

In [39]:
dp_ans = pd.DataFrame(dp_test['alert_key'])
dp_ans['probability'] = dp_y_ans[0]
dp_ans

alert_key  probability
0         352249          0.0
1         352249          0.0
2         352249          0.0
3         352249          0.0
4         352249          0.0
...          ...          ...
13546     364993          0.0
13547     364993          0.0
13548     364993          0.0
13549     364993          0.0
13550     364993          0.0

[13551 rows x 2 columns]

In [40]:
remit_ans = pd.DataFrame(remit_test['alert_key'])
remit_ans['probability'] = remit_y_ans[0]
remit_ans

alert_key  probability
0       352253          0.0
1       354177          0.0
2       354569          0.0
3       355347          0.0
4       356569          0.0
..         ...          ...
532     364673          0.0
533     364753          0.0
534     364775          0.0
535     364788          0.0
536     364993          0.0

[537 rows x 2 columns]

In [41]:
ans = pd.concat([cdtx_ans,dp_ans,remit_ans])

In [42]:
ans

alert_key  probability
0       352291          0.0
1       352291          0.0
2       352298          0.0
3       352298          0.0
4       353041          0.0
..         ...          ...
532     364673          0.0
533     364753          0.0
534     364775          0.0
535     364788          0.0
536     364993          0.0

[16216 rows x 2 columns]

In [44]:
ans['probability'] = ans['probability'].abs()

In [45]:
ans_mean = ans.groupby(['alert_key']).mean()

In [46]:
ans_mean


probability
alert_key             
352249        0.000000
352253        0.000000
352254        0.000000
352280        0.000000
352282        0.000000
...                ...
365001        0.000000
365004        0.000000
365008        0.000000
365009        0.013333
365073        0.000000

[1528 rows x 1 columns]

In [47]:
submit = pd.read_csv('/home/bill/moneylaundring/dataset/submit.csv')

In [48]:
submit['probability']=0

In [49]:
submit_new = pd.merge(submit, ans_mean, on=['alert_key'],how='left')

In [50]:
submit_new['probability_y'].fillna(0,inplace=True)

In [51]:
submit_final = submit_new.rename(columns={'probability_y':'probability'})

In [52]:
submit_final = submit_final[['alert_key','probability']]

In [53]:
submit_final = submit_final.sort_values(by ='probability', ascending=False)

In [54]:
submit_final

alert_key  probability
57       354047     0.526543
341      360833     0.513333
1410     364223     0.387083
3264     355759     0.234444
975      354810     0.227778
...         ...          ...
1334     356589     0.000000
1335     361144     0.000000
1336     367544     0.000000
1337     358470     0.000000
3849     372119     0.000000

[3850 rows x 2 columns]

In [55]:
submit_final.to_csv('/home/bill/moneylaundring/contest/submissions/random_forest.csv')