## Score : 0.006447	

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cdtx_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/cdtx_train.csv')
dp_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/dp_train.csv')
remit_train = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/remit_train.csv')
cdtx_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/cdtx_test_private.csv')
dp_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/dp_test_private.csv')
remit_test = pd.read_csv('/home/bill/moneylaundring/contest/processed_dataset/remit_test_private.csv')

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor

In [4]:
cdtx_X = cdtx_train.iloc[:,1:-1].values
cdtx_y = cdtx_train.iloc[:,-1].values

In [5]:
dp_X = dp_train.iloc[:,1:-1].values
dp_y = dp_train.iloc[:,-1].values

In [6]:
remit_X = remit_train.iloc[:,1:-1].values
remit_y = remit_train.iloc[:,-1].values

In [7]:
cdtx_test_new = cdtx_test.iloc[:,1:].values

In [8]:
dp_test_new = dp_test.iloc[:,1:].values

In [9]:
remit_test_new = remit_test.iloc[:,1:].values

In [10]:
cdtx_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,5,8]),('standardscaler',StandardScaler(),[2,6,7])], remainder='passthrough')
cdtx_X = cdtx_ct.fit_transform(cdtx_X)
cdtx_X

<48107x366 sparse matrix of type '<class 'numpy.float64'>'
	with 432963 stored elements in Compressed Sparse Row format>

In [11]:
dp_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,5,6,8,9,10,11,12,13,15]),('standardscaler',StandardScaler(),[2,7,14])], remainder='passthrough')
dp_X = dp_ct.fit_transform(dp_X)
dp_X

<164030x1874 sparse matrix of type '<class 'numpy.float64'>'
	with 2624480 stored elements in Compressed Sparse Row format>

In [12]:
remit_ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(handle_unknown='ignore'),[0,1,3,4,7]),('standardscaler',StandardScaler(),[2,5,6])], remainder='passthrough')
remit_X = remit_ct.fit_transform(remit_X)
remit_X

<5438x280 sparse matrix of type '<class 'numpy.float64'>'
	with 43504 stored elements in Compressed Sparse Row format>

In [13]:
cdtx_test_X = cdtx_ct.transform(cdtx_test_new)

In [14]:
dp_test_X = dp_ct.transform(dp_test_new)

In [15]:
remit_test_X = remit_ct.transform(remit_test_new)

In [16]:
regressor_cdtx = RandomForestRegressor(n_estimators=100, criterion='mse', random_state= 42)
regressor_cdtx.fit(cdtx_X, cdtx_y)

/home/bill/anaconda3/envs/moneylaundring/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


RandomForestRegressor(criterion='mse', random_state=42)

In [18]:
cdtx_X.shape

(48107, 366)

In [17]:
regressor_dp = RandomForestRegressor(n_estimators=100, criterion='mse', random_state= 42)
regressor_dp.fit(dp_X, dp_y)

/home/bill/anaconda3/envs/moneylaundring/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


KeyboardInterrupt: 

In [ ]:
regressor_remit = RandomForestRegressor(n_estimators=100, criterion='mse', random_state= 42)
regressor_remit.fit(remit_X, remit_y)

/home/bill/anaconda3/envs/moneylaundring/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


RandomForestRegressor(criterion='mse', random_state=42)

In [ ]:
cdtx_y_pred = regressor_cdtx.predict(cdtx_test_X)
cdtx_y_pred

array([0.  , 0.  , 0.04, ..., 0.  , 0.  , 0.  ])

In [ ]:
cdtx_y_ans = pd.DataFrame(cdtx_y_pred)

In [ ]:
cdtx_y_ans[cdtx_y_ans[0]!=0]

0
2     0.04
3     0.04
4     0.04
5     0.04
6     0.04
7     0.04
8     0.04
9     0.04
10    0.04
117   0.06
1711  0.07
1712  0.07

In [ ]:
dp_y_pred = regressor_dp.predict(dp_test_X)
dp_y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
dp_y_ans = pd.DataFrame(dp_y_pred)
dp_y_ans

0
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
...    ...
14834  0.0
14835  0.0
14836  0.0
14837  0.0
14838  0.0

[14839 rows x 1 columns]

In [ ]:
remit_y_pred = regressor_remit.predict(remit_test_X)
remit_y_pred

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.

In [ ]:
remit_y_ans = pd.DataFrame(remit_y_pred)
remit_y_ans

0
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
..   ...
624  0.0
625  0.0
626  0.0
627  0.0
628  0.0

[629 rows x 1 columns]

In [ ]:
cdtx_ans = pd.DataFrame(cdtx_test['alert_key'])
cdtx_ans['probability'] = cdtx_y_ans[0]
cdtx_ans

alert_key  probability
0        368186         0.00
1        373816         0.00
2        365768         0.04
3        368081         0.04
4        368850         0.04
...         ...          ...
1793     377924         0.00
1794     377924         0.00
1795     378240         0.00
1796     378404         0.00
1797     378407         0.00

[1798 rows x 2 columns]

In [ ]:
dp_ans = pd.DataFrame(dp_test['alert_key'])
dp_ans['probability'] = dp_y_ans[0]
dp_ans

alert_key  probability
0         365126          0.0
1         365126          0.0
2         365126          0.0
3         365126          0.0
4         365126          0.0
...          ...          ...
14834     378428          0.0
14835     378428          0.0
14836     378428          0.0
14837     378428          0.0
14838     378428          0.0

[14839 rows x 2 columns]

In [ ]:
remit_ans = pd.DataFrame(remit_test['alert_key'])
remit_ans['probability'] = remit_y_ans[0]
remit_ans

alert_key  probability
0       365126          0.0
1       368186          0.0
2       374259          0.0
3       365195          0.0
4       365768          0.0
..         ...          ...
624     377358          0.0
625     377457          0.0
626     377933          0.0
627     378076          0.0
628     378428          0.0

[629 rows x 2 columns]

In [ ]:
ans = pd.concat([cdtx_ans,dp_ans,remit_ans])

In [ ]:
ans

alert_key  probability
0       368186         0.00
1       373816         0.00
2       365768         0.04
3       368081         0.04
4       368850         0.04
..         ...          ...
624     377358         0.00
625     377457         0.00
626     377933         0.00
627     378076         0.00
628     378428         0.00

[17266 rows x 2 columns]

In [ ]:
ans['probability'] = ans['probability'].abs()

In [ ]:
ans_mean = ans.groupby(['alert_key']).max()

In [ ]:
ans_mean


probability
alert_key             
365126            0.00
365166            0.00
365167            0.00
365180            0.02
365186            0.00
...                ...
378410            0.00
378414            0.00
378426            0.00
378427            0.00
378428            0.00

[1698 rows x 1 columns]

In [ ]:
submit = pd.read_csv('/home/bill/moneylaundring/dataset/submit.csv')

In [ ]:
submit['probability']=0

In [ ]:
submit_new = pd.merge(submit, ans_mean, on=['alert_key'],how='left')

In [ ]:
submit_new['probability_y'].fillna(0,inplace=True)

In [ ]:
submit_final = submit_new.rename(columns={'probability_y':'probability'})

In [ ]:
submit_final = submit_final[['alert_key','probability']]

In [ ]:
submit_final = submit_final.sort_values(by ='probability', ascending=False)

In [ ]:
submit_final

alert_key  probability
1876     377349         0.66
3669     376670         0.39
3134     373827         0.39
3451     376350         0.39
2669     374456         0.39
...         ...          ...
1329     352880         0.00
1330     378230         0.00
1331     376336         0.00
1334     356589         0.00
3849     372119         0.00

[3850 rows x 2 columns]

In [ ]:
submit_final.to_csv('/home/bill/moneylaundring/contest/submissions/random_forest_private.csv')